-- MySQL Script generated by MySQL Workbench
-- 08/01/16 16:34:34
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema astdialerdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema astdialerdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `astdialerdb` DEFAULT CHARACTER SET utf8 ;
USE `astdialerdb` ;

-- -----------------------------------------------------
-- Table `astdialerdb`.`campaings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `astdialerdb`.`campaings` ;

CREATE TABLE IF NOT EXISTS `astdialerdb`.`campaings` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `state` VARCHAR(10) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `max_retries` INT(11) NOT NULL,
  `max_calls` INT(11) NOT NULL,
  `prefix` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `astdialerdb`.`configs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `astdialerdb`.`configs` ;

CREATE TABLE IF NOT EXISTS `astdialerdb`.`configs` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `parameter` VARCHAR(100) NOT NULL,
  `value` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `astdialerdb`.`numberlist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `astdialerdb`.`numberlist` ;

CREATE TABLE IF NOT EXISTS `astdialerdb`.`numberlist` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `prefix` VARCHAR(5) NOT NULL,
  `phonenumber` VARCHAR(20) NOT NULL,
  `state` INT(11) NULL DEFAULT '0',
  `campaing_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `campaing_id`),
  INDEX `FK_CAMPAING_ID` (`campaing_id` ASC),
  CONSTRAINT `FK_CAMPAING_ID`
    FOREIGN KEY (`campaing_id`)
    REFERENCES `astdialerdb`.`campaings` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `astdialerdb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `astdialerdb`.`users` ;

CREATE TABLE IF NOT EXISTS `astdialerdb`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL DEFAULT NULL,
  `username` VARCHAR(50) NULL DEFAULT NULL,
  `password` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
